### PR TITLE
Case insensitive LIKE filters

### PR DESCRIPTION
**Pull request by plfort**
Add ILIKE, NILIKE, LILIKE, RILIKE operators (case insensitive search)
add en and fr translation for ilike,rilike nilike,lilike
Reference #679

It's just an implementation suggestion, the other option would be to add a $caseSensitive boolean field in Filter to avoid duplication of operators;

### CODE REVIEW

**Comment by Abhoryo** [comment]
These add some BBC but it's ok. Can you complete the documentation too ?

**Comment by plfort** [comment]
I thought about BC, I could change the code to make LIKE filter case insentitive by default and change ILIKE to SLIKE (for Sensitive Like). I think it will reduce the impact because most of users expect LIKE to be insensitive (I may be wrong). What do you think ?
Ok for the doc :)

**Comment by Abhoryo** [comment]
Yes SLIKE would be great, It can also mean "Strict" too.
Plus, we avoid some legal issues with Apple!

**Comment by plfort** [comment]
Is it ok for you ?

**Comment by Abhoryo** [comment]
Yep good for me, thanks.

**Pull request merged**
