### PR TITLE
YAML file configuration and Command to generate YML from an entity

### PR DESCRIPTION
**Pull request by npotier**
Hi,

After few talks about it, here is a pull request to add yml file configuration and a command to generate theses file from an entity.

YML file configuration
-------------------------------
- Like doctrine, YML file configuration for an entity must be placed in a special directory and have a special name MyBundle/Resources/config/grid/MyEntity.myGroup.grid.yml
- The YML file structure is the following:
````
# Resources/config/grid/MyEntity.myGroup.grid.yml
namespace\of\MyEntity
    Source:
        columns: 
            id: ~
            myColumn1: ~
        groupBy: ~
        filterable: ~
    Columns:
        id:
            filterable: true
            visible: true
            id: id
            title: columnTitle
        myColumn1: ....
    ...
````
- Annotation and YML Driver are both loaded in services.xml

YML Generation command
-------------------------------
- The command will allow you to generate a YML config file for an entity and a group:

```
php app/console apydatagrid:generate:grid --entity="MyBundle:MyEntity" --group="default"
```

- The file will be generated and written in src/MyBundle/Resources/config/grid/MyEntity.default.grid.yml.
- The generation of the file is based on a skeleton template stored in APYDataGrid/Resourses/skeleton/grid/grid.yml.twig.

Feel free to make any comments on this PR !

### CODE REVIEW

**Comment by npotier** [comment]
Hello / Salut @Abhoryo. Avant tout, bonne année ;)

Peux tu me dire ce qu'il manquerait à cette PR pour être mergée ?

Merci.

Nicolas.

**Comment by Abhoryo** [comment]
Salut, @npotier , Pourrais-tu corriger le fichier summary qui a plein de tabulations.
Je mergerai quand ce sera fait, tant pis pour la régression.

**Comment by phpetra** [comment]
Hi guys,
Can I ask about the status of this PR?
My french is not so good, what exactly needs to be done?

**Comment by Abhoryo** [comment]
Wait for a modification from @npotier and this is good for merge.

**Comment by npotier** [comment]
Salut @Abhoryo, c'est fait. A ta dispo pour avancer.

Nicolas.

**Comment by npotier** [comment]
Hourra :)

Merci.

**Comment by phpetra** [comment]
Nice indeed! :)

**Comment by qferr** [comment]
+1

**Comment by Abhoryo** [comment]
@npotier can you do something about exceptions that everyone encounter ?

**Pull request merged**
